# -*- coding: utf-8 -*-
"""Veridian.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15VX93HbWrlDV-1eK1KlE5qxzHVk7H1JS
"""

user_query = input("Enter a company name: ")

!pip install -q --upgrade google-generativeai

import google.generativeai as genai
from google.api_core import exceptions
import os

# --- PASTE YOUR *NEW* KEY HERE ---
# Do not use the key starting with AIza...khC_fE (it is exposed)
MY_API_KEY = "AIzaSyBxsTCKkX1NlvUldxBfJM9g-qBdtkhC_fE" # <--- PLEASE REPLACE THIS WITH YOUR VALID API KEY

genai.configure(api_key=MY_API_KEY)

def get_ticker_symbol(user_input):
    # Use the alias that worked for your list
    model = genai.GenerativeModel('gemini-flash-latest')

    prompt = f"""
    You are a strict financial data converter.
    Input: "{user_input}"
    Task: Convert to the correct stock ticker symbol (e.g., AAPL).
    Rules:
    - Output ONLY the ticker.
    - If invalid/private, output "ERROR: Ticker not found".
    """

    try:
        response = model.generate_content(prompt)
        return response.text.strip()
    except Exception as e:
        return f"ERROR: {e}"

result = get_ticker_symbol(user_query)
print(f"ticker: {result}")

!pip install -q pandas requests beautifulsoup4 transformers torch sentence-transformers pytrends accelerate yfinance feedparser
!pip install praw

!pip install xgboost

def AlternateWeb(result):
  # ==============================
  # AltFusion-XGB (Ticker Input Version)
  # ==============================

  # ---------- INSTALL (run once) ----------
  # !pip install transformers xgboost yfinance pytrends requests scikit-learn joblib praw

  import os
  import time
  import requests
  import joblib
  import re
  import numpy as np
  import pandas as pd
  import yfinance as yf
  from datetime import datetime
  import concurrent.futures

  from transformers import pipeline
  from xgboost import XGBRegressor
  from pytrends.request import TrendReq
  from pytrends.exceptions import TooManyRequestsError
  import praw

  # ==============================
  # 1️⃣ Sentiment Model (LOCKED)
  # ==============================
  sentiment_analyzer = pipeline(
      "sentiment-analysis",
      model="distilbert/distilbert-base-uncased-finetuned-sst-2-english",
      revision="714eb0f"
  )

  # ==============================
  # 2️⃣ Reddit API (READ-ONLY)
  # ==============================
  reddit = praw.Reddit(
      client_id="lXVCupaZFzxD8prEGbTIiw",
      client_secret="saca9k8m_jLT0CVVZzCWwjwGti6jzA",
      user_agent="Mozilla/5.0 (InvestmentAnalyzer/1.0)"
  )

  def get_reddit_sentiment(company_name, subreddits):
      """Uses official Reddit API via PRAW."""
      try:
          all_titles = []
          # Search for the main company name
          search_term = company_name

          for sub in subreddits:
              # Limit to 25 posts per sub to save API calls
              for submission in reddit.subreddit(sub).search(search_term, sort="new", limit=25):
                  all_titles.append(submission.title)

          if not all_titles:
              print(f"⚠️ No posts found for '{company_name}' on Reddit.")
              return 0, 0

          sample_titles = all_titles[:50]
          sentiments = sentiment_analyzer(sample_titles)
          score = sum(1 if s["label"] == "POSITIVE" else -1 for s in sentiments)
          return round(score / len(sentiments), 3), len(all_titles)

      except Exception as e:
          print(f"❌ Reddit API error: {e}")
          return 0, 0



  # ==============================
  # 3️⃣ GitHub Commits
  # ==============================
  def fetch_github_commits(org):
      try:
          repos = requests.get(
              f"https://api.github.com/orgs/{org}/repos", timeout=10
          ).json()

          if not isinstance(repos, list):
              return 0

          total = 0
          for r in repos[:5]:
              commits_url = r["commits_url"].replace("{/sha}", "")
              commits = requests.get(commits_url, timeout=10).json()
              if isinstance(commits, list):
                  total += len(commits)

          return total
      except Exception:
          return 0


  # ==============================
  # 4️⃣ Job Postings (Adzuna)
  # ==============================
  def fetch_job_postings(keyword):
      app_id = "ab4c753e"
      app_key = "b20e95cc52342837df4285c25d2c50d4"
      url = f"https://api.adzuna.com/v1/api/jobs/in/search/1?app_id={app_id}&app_key={app_key}&what={keyword}"
      try:
          resp = requests.get(url).json()
          return len(resp.get("results", []))
      except:
          return 0


  # ==============================
  # 5️⃣ Google Trends
  # ==============================
  def fetch_trend_score(keyword, retries=3):
      for attempt in range(retries):
          try:
              pytrends = TrendReq(hl="en-US", tz=360)
              pytrends.build_payload([keyword], timeframe="today 3-m")
              data = pytrends.interest_over_time()
              if data.empty:
                  return 0
              return int(data[keyword].iloc[-1] - data[keyword].iloc[0])
          except TooManyRequestsError:
              time.sleep(10 * (attempt + 1))
          except Exception:
              return 0
      return 0


  # ==============================
  # 6️⃣ Feature Collector
  # ==============================
  def collect_features(keyword, github_org):
      subs = ["stocks", "investing", "wallstreetbets", "StockMarket"]

      with concurrent.futures.ThreadPoolExecutor() as executor:
          f_reddit = executor.submit(get_reddit_sentiment, keyword, subs)
          f_git = executor.submit(fetch_github_commits, github_org)
          f_jobs = executor.submit(fetch_job_postings, keyword)
          f_trends = executor.submit(fetch_trend_score, keyword)

          reddit_score, reddit_vol = f_reddit.result()

          return {
              "timestamp": datetime.now(),
              "reddit_sentiment": reddit_score,
              "reddit_volume": reddit_vol,
              "github_commits": f_git.result(),
              "job_postings": f_jobs.result(),
              "trend_score": f_trends.result(),
          }


  # ==============================
  # 7️⃣ Fallback Score
  # ==============================
  def fallback_investment_score(f):
      score = 0
      score += f["reddit_sentiment"] * 30
      score += np.log1p(f["github_commits"]) * 10
      score += np.log1p(f["job_postings"]) * 15
      score += f["trend_score"] * 0.5
      return float(score)


  # ==============================
  # 8️⃣ XGBoost
  # ==============================
  def train_xgb_model(csv_path, model_path):
      df = pd.read_csv(csv_path)
      if len(df) < 10:
          return None

      X = df[[
          "reddit_sentiment",
          "github_commits",
          "job_postings",
          "trend_score"
      ]]
      y = df["target_score"]

      model = XGBRegressor(
          n_estimators=200,
          learning_rate=0.05,
          max_depth=4,
          subsample=0.8,
          colsample_bytree=0.8,
          random_state=42
      )

      model.fit(X, y)
      joblib.dump(model, model_path)
      return model


  def predict_xgb(features, model_path):
      model = joblib.load(model_path)
      X = pd.DataFrame([features])[[
          "reddit_sentiment",
          "github_commits",
          "job_postings",
          "trend_score"
      ]]
      return float(model.predict(X)[0])


  # ==============================
  # 9️⃣ Ticker Resolver
  # ==============================
  def get_company_info(ticker):
      try:
          stock = yf.Ticker(ticker)
          name = stock.info.get("shortName") or stock.info.get("longName")
          if not name:
              return ticker, ticker.lower()

          clean = re.sub(
              r'[\,\.]?\s*(Inc|Corp|Corporation|Ltd|PLC|Group|Holdings|Company)\.?$',
              '',
              name,
              flags=re.IGNORECASE
          ).strip()

          github_guess = clean.replace(" ", "").lower()
          return clean, github_guess

      except Exception:
          return ticker, ticker.lower()


  # ==============================
  # 🔟 OUTPUT FORMATTER (REQUIRED)
  # ==============================
  def format_prediction_output(score, features):
      s = np.clip(score, -100, 100)

      buy = max(0, s) / 100
      sell = max(0, -s) / 100
      hold = 1 - (buy + sell)

      total = buy + sell + hold
      buy, sell, hold = buy / total, sell / total, hold / total

      confidence = round(abs(s) / 100, 2)

      reasons = []
      if features["reddit_sentiment"] > 0.1:
          reasons.append("Positive Reddit sentiment")
      elif features["reddit_sentiment"] < -0.1:
          reasons.append("Negative Reddit sentiment")

      if features["github_commits"] > 100:
          reasons.append("Strong developer activity")

      if features["job_postings"] > 10:
          reasons.append("Hiring momentum")

      if features["trend_score"] > 10:
          reasons.append("Rising public interest")
      elif features["trend_score"] < -10:
          reasons.append("Declining public interest")

      if not reasons:
          reasons.append("Mixed signals with no strong directional bias")

      return {
          "prediction": [round(buy, 2), round(sell, 2), round(hold, 2)],
          "confidence": confidence,
          "reason": "; ".join(reasons)
      }


  # ==============================
  # 🔟 MAIN
  # ==============================
  def main():
      ticker = result

      keyword, github_org = get_company_info(ticker)

      features = collect_features(keyword, github_org)
      features["target_score"] = fallback_investment_score(features)

      data_path = "altfusion_data.csv"
      model_path = "altfusion_xgb.pkl"

      if os.path.exists(data_path):
          df = pd.read_csv(data_path)
          df = pd.concat([df, pd.DataFrame([features])], ignore_index=True)
      else:
          df = pd.DataFrame([features])

      df.to_csv(data_path, index=False)

      if not os.path.exists(model_path) and len(df) >= 10:
          train_xgb_model(data_path, model_path)

      if os.path.exists(model_path):
          score = predict_xgb(features, model_path)
      else:
          score = fallback_investment_score(features)

      output = format_prediction_output(score, features)

      print("\n📤 Model Output:")
      print(output)
      return output


  return main()

def MacroEconomic_Analysis(ticker):
    import json
    import joblib
    import yfinance as yf
    import pandas as pd
    import numpy as np
    import requests
    from pathlib import Path

    # ----------------------------
    # Paths
    # ----------------------------
    MODEL_DIR = Path("/content/drive/MyDrive/Veridian/Macro")
    MODEL_PATH = MODEL_DIR / "xgb_macro.joblib"
    SCALER_PATH = MODEL_DIR / "scaler.joblib"
    META_PATH = MODEL_DIR / "meta.json"

    # ----------------------------
    # Load artifacts
    # ----------------------------
    model = joblib.load(MODEL_PATH)
    scaler = joblib.load(SCALER_PATH)
    meta = json.load(open(META_PATH))

    FEATURES = meta["features"]

    # ----------------------------
    # World Bank helpers
    # ----------------------------
    WB_INDICATORS = {
        "gdp_growth": "NY.GDP.MKTP.KD.ZG",
        "inflation": "FP.CPI.TOTL.ZG",
        "unemployment": "SL.UEM.TOTL.ZS",
    }

    INDEX_COUNTRY_MAP = {
        "^GSPC": "United States",
        "^DJI": "United States",
        "^IXIC": "United States",
        "^NSEI": "India",
    }

    def to_month_end(d):
        return pd.to_datetime(d).to_period("M").to_timestamp("M")

    def fetch_country_iso_map():
        url = "https://api.worldbank.org/v2/country?format=json&per_page=400"
        rows = requests.get(url, timeout=30).json()[1]
        return {r["name"]: r["iso2Code"] for r in rows if r["iso2Code"]}

    COUNTRY_ISO = fetch_country_iso_map()

    def resolve_country(t):
        info = yf.Ticker(t).info
        return info.get("country") or INDEX_COUNTRY_MAP.get(t)

    def fetch_macro_country(iso2):
        frames = []
        for name, code in WB_INDICATORS.items():
            url = f"https://api.worldbank.org/v2/country/{iso2}/indicator/{code}?format=json&per_page=2000"
            data = requests.get(url, timeout=30).json()
            if not data or data[1] is None:
                return None
            df = pd.DataFrame(data[1])[["date", "value"]].dropna()
            df["date"] = pd.to_datetime(df["date"] + "-12-31").apply(to_month_end)
            df.rename(columns={"value": name}, inplace=True)
            frames.append(df)

        m = frames[0]
        for f in frames[1:]:
            m = m.merge(f, on="date", how="outer")

        return m.sort_values("date").interpolate().ffill()

    # ----------------------------
    # Inference
    # ----------------------------
    country = resolve_country(ticker)
    if not country or country not in COUNTRY_ISO:
        return {
            "prediction": [0.33, 0.33, 0.34],
            "confidence": 0.2,
            "reason": "Macroeconomic data unavailable for this region.",
            "model": "Macro"
        }

    macro = fetch_macro_country(COUNTRY_ISO[country])
    if macro is None:
        return {
            "prediction": [0.33, 0.33, 0.34],
            "confidence": 0.2,
            "reason": "Insufficient macroeconomic indicators.",
            "model": "Macro"
        }

    last = macro.iloc[-1]
    X = pd.DataFrame([last[FEATURES]])
    Xs = scaler.transform(X)

    p_buy = float(model.predict_proba(Xs)[0, 1])
    p_sell = 1 - p_buy
    p_hold = 1 - abs(p_buy - 0.5) * 2

    confidence = round(max(p_buy, p_sell), 2)

    reason = (
        "Supportive macro conditions (GDP growth, inflation, employment)"
        if p_buy > 0.55
        else "Macroeconomic headwinds detected"
        if p_sell > 0.55
        else "Neutral macroeconomic environment"
    )

    output = {
        "prediction": [round(p_buy, 2), round(p_sell, 2), round(p_hold, 2)],
        "confidence": confidence,
        "reason": reason,
        "model": "Macro"
    }

    # 👇 ADD THIS LINE TO SEE THE RESULT
    print(f"📊 Macro Output: {output}")

    return output

import os
from google.colab import drive
os.makedirs('content', exist_ok=True)
drive.mount('/content/drive')

!pip install torch transformers datasets scikit-learn
!pip install -q transformers datasets accelerate sentencepiece pyarrow lxml_html_clean newspaper3k feedparser
!pip install -q -U transformers datasets accelerate sentencepiece pyarrow
!python -m spacy download en_core_web_sm

def NewsAnalysis(result):

    import os, math, time, re
    import numpy as np
    import torch
    import feedparser
    from transformers import AutoTokenizer, AutoModelForSequenceClassification
    from newspaper import Article
    from urllib.parse import quote_plus
    from bs4 import BeautifulSoup
    from typing import List, Dict
    import spacy

    result = result.replace(".NS","").replace(".BO","")

    # ================= CONFIG =================
    DRIVE_MODEL_PATH = "/content/drive/MyDrive/Veridian/finbert_financial_mixed"


    SOURCE_WEIGHTS = {
        "twitter": 0.6,
        "google_news": 1.0,
        "economic_times": 1.0,
        "cnbc": 1.1,
        "investing_com": 0.9,
        "yahoo_finance": 1.0,
        "reuters": 1.1,
        "bloomberg": 1.2,
        "default": 1.0
    }

    RECENCY_LAMBDA = 0.02
    MAX_NEWS = 5
    MAX_TWEETS = 50

    # ================= NLP =================
    try:
        nlp = spacy.load("en_core_web_sm")
    except:
        nlp = None

    # ================= LOAD MODEL =================
    try:
        tokenizer = AutoTokenizer.from_pretrained(DRIVE_MODEL_PATH)
        model = AutoModelForSequenceClassification.from_pretrained(DRIVE_MODEL_PATH)
        model.eval()
        if torch.cuda.is_available():
            model.to("cuda")
    except:
        return {
            "prediction":[0.33,0.33,0.34],
            "confidence":0.0,
            "reason":"Sentiment model not loaded"
        }

    # ================= CLEAN =================
    def clean_text(text):
        if not text or len(text)<50: return text
        footers=["read more","copyright","privacy policy","subscribe now","click here"]
        for f in footers:
            if f in text.lower():
                text=text[:text.lower().find(f)]
        return text.strip()

    # ================= SCRAPE NEWS =================
    def scrape_news(query):
        items=[]
        term=quote_plus(query)
        sources=[
            ("google_news",f"https://news.google.com/rss/search?q={term}&hl=en-US&gl=US&ceid=US:en",1.0),
            ("economic_times","https://economictimes.indiatimes.com/markets/stocks/rssfeeds/2146842.cms",1.0),
            ("cnbc","https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=10000664",1.1),
            ("investing_com","https://www.investing.com/rss/stock_Market.rss",0.9),
            ("yahoo_finance","https://finance.yahoo.com/news/rssindex",0.9)
        ]

        for name,url,w in sources:
            feed=feedparser.parse(url)
            for e in feed.entries:
                if len(items)>=MAX_NEWS: break
                title=e.get("title","")
                summary=e.get("summary","")
                link=e.get("link","")

                if summary:
                    summary=BeautifulSoup(summary,"html.parser").get_text()

                combined=(title+" "+summary).lower()
                if result.lower().split()[0] not in combined:
                    continue

                text=f"{title}\n\n{summary}"

                if link and len(text)<200:
                    try:
                        art=Article(link)
                        art.download(); art.parse()
                        if len(art.text)>200:
                            text=f"{art.title}\n\n{art.text}"
                    except: pass

                text=clean_text(text)

                if len(text)>60:
                    items.append({
                        "text":text,
                        "source":name,
                        "source_weight":w,
                        "timestamp":time.time()
                    })
        return items

    # ================= SCRAPE TWEETS =================
    def scrape_tweets(query):
        try:
            import snscrape.modules.twitter as sntwitter
        except:
            return []
        items=[]
        q=f"{query} since:2024-11-01"
        for i,t in enumerate(sntwitter.TwitterSearchScraper(q).get_items()):
            if i>=MAX_TWEETS: break
            items.append({
                "text":t.rawContent,
                "source":"twitter",
                "source_weight":SOURCE_WEIGHTS["twitter"],
                "timestamp":t.date.timestamp()
            })
        return items

    # ================= SENTIMENT =================
    def predict_sentiment(text, entity=None):

      if entity:
          inputs = tokenizer(text, text_pair=entity,
                            return_tensors="pt",
                            truncation=True, padding=True, max_length=128)
      else:
          inputs = tokenizer(text,
                            return_tensors="pt",
                            truncation=True, padding=True, max_length=128)

      if torch.cuda.is_available():
          inputs = {k:v.to("cuda") for k,v in inputs.items()}

      with torch.no_grad():
          out = model(**inputs)

      logits = out.logits.cpu().numpy()[0]

      import torch.nn.functional as F
      probs = F.softmax(torch.tensor(logits), dim=-1).numpy()

      label_map = model.config.id2label

      p_raw = {label_map[i].lower(): probs[i] for i in range(len(probs))}

      positive = p_raw.get("positive", 0)
      negative = p_raw.get("negative", 0)

      neutral = max(0, 1 - abs(positive - negative))

      total = positive + negative + neutral

      p = {
          "positive": positive/total,
          "negative": negative/total,
          "neutral": neutral/total
      }

      sentiment_value = p["positive"] - p["negative"]
      confidence = max(p.values())

      return p, sentiment_value, confidence


    # ================= RECENCY =================
    def recency(ts):
        return math.exp(-RECENCY_LAMBDA*((time.time()-ts)/3600))

    # ================= EVENT =================
    def extract_event(text):
        if not text: return "No information available"
        patterns=[r'earnings',r'acquire',r'merger',r'strike',r'bankruptcy',
                  r'launch',r'recall',r'surge',r'plunge']
        for p in patterns:
            m=re.search(p,text,re.I)
            if m:
                s=max(0,m.start()-40); e=min(len(text),m.end()+60)
                return text[s:e]
        if nlp:
            doc=nlp(text[:400])
            for s in doc.sents:
                if len(s.text)>20:
                    return s.text[:120]
        return text[:120]

    # ================= AGGREGATE =================
    def aggregate(items):
        ap=an=ag=den=0
        confs=[]; srcs=[]
        best=None; best_score=-1

        for it in items:
            w=recency(it["timestamp"])*it["source_weight"]
            probs,sv,conf=predict_sentiment(it["text"],result)

            ap+=w*probs["positive"]
            an+=w*probs["negative"]
            ag+=w*probs["neutral"]
            den+=w

            confs.append(conf)
            srcs.append(it["source_weight"])

            if w*conf>best_score:
                best_score=w*conf
                best=it["text"]

        if den>0:
            ap/=den; an/=den; ag/=den
        else:
            ap=an=ag=1/3

        prediction=[float(ap),float(an),float(ag)]

        c_model=np.mean(confs) if confs else 0
        c_source=np.mean(srcs)/max(SOURCE_WEIGHTS.values()) if srcs else 0
        c_volume=min(1,math.log(1+len(items))/math.log(101))

        confidence=0.65*c_model+0.25*c_source+0.10*c_volume

        return {
            "prediction":prediction,
            "confidence":round(float(confidence),4),
            "reason":extract_event(best) if best else "No data"
        }

    # ================= RUN =================
    news=scrape_news(f"{result} stock")
    tweets=scrape_tweets(result)
    items=news+tweets

    return aggregate(items)

!pip install -q newspaper3k lxml_html_clean snscrape feedparser

!pip install lightgbm

def Fundamental_Analysis(result):
  # ==============================================================================
  # 1. GLOBAL SUPPORT: Works for US (BLK) and India (AXISBANK) automatically.
  # 2. STRICT SCORING: No free points. Banks need ROA > 1% to get high scores.
  # 3. TREND VETO: Even if Score is 9/9, we HOLD if the Trend is Down.
  # 4. OUTPUT: Strict JSON for API integration.
  # ==============================================================================

  import os
  import time
  import warnings
  import numpy as np
  import pandas as pd
  import torch
  import torch.nn as nn
  import lightgbm as lgb
  import yfinance as yf
  from sklearn.preprocessing import StandardScaler
  from google.colab import drive

  warnings.filterwarnings('ignore')

  # --- 1. CONFIGURATION & DRIVE ---
  SEQ_LEN = 90
  INPUT_DIM = 8
  HIDDEN_DIM = 128
  EMBEDDING_DIM = 32

  drive.mount('/content/drive')
  LOAD_PATH = '/content/drive/My Drive/Veridian/Veridian_Models/'

  # --- 2. DEFINE MODEL ARCHITECTURE ---
  class LSTMEncoder(nn.Module):
      def __init__(self):
          super(LSTMEncoder, self).__init__()
          self.lstm = nn.LSTM(INPUT_DIM, HIDDEN_DIM, num_layers=2, batch_first=True, dropout=0.2)
          self.projection = nn.Linear(HIDDEN_DIM, EMBEDDING_DIM)
          self.relu = nn.ReLU()

      def forward(self, x):
          out, _ = self.lstm(x)
          return self.relu(self.projection(out[:, -1, :]))

  # --- 3. LOAD MODELS ---
  try:
      if not os.path.exists(f"{LOAD_PATH}veridian_titan_lstm.pth"):
          raise FileNotFoundError("Model files not found!")

      lstm_model = LSTMEncoder()
      lstm_model.load_state_dict(torch.load(f"{LOAD_PATH}veridian_titan_lstm.pth", map_location=torch.device('cpu')))
      lstm_model.eval()

      bst_model = lgb.Booster(model_file=f"{LOAD_PATH}veridian_titan_lgb.txt")
      print("✅ System Online.")
  except Exception as e:
      print(f"❌ Critical Error Loading Models: {e}")

  # --- 4. DATA ENGINE ---
  def process_data(ticker):
      stock = yf.Ticker(ticker)
      df = stock.history(period="2y")

      if len(df) < SEQ_LEN + 10: return None, None, None

      # Calculate Features
      eps = stock.info.get('trailingEps', 0)
      if eps is None or eps <= 0: eps = df['Close'].iloc[-1] / 20.0
      df['Synthetic_PE'] = df['Close'] / eps
      df['SMA_50'] = df['Close'].rolling(window=50).mean()

      delta = df['Close'].diff()
      gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
      loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
      rs = gain / loss
      df['RSI'] = 100 - (100 / (1 + rs))
      df.fillna(0, inplace=True)

      features = ['Open', 'High', 'Low', 'Close', 'Volume', 'SMA_50', 'RSI', 'Synthetic_PE']
      raw = df[features].values
      scaler = StandardScaler()
      scaled = scaler.fit_transform(raw)

      info = stock.info
      fund = [info.get('debtToEquity', 50.0), info.get('profitMargins', 0.1), info.get('returnOnEquity', 0.15)]
      fund = [x if x is not None else 0 for x in fund]

      return scaled, fund, df['Close'].iloc[-1]

  # --- 5. STRICT SECTOR ENGINE (Adaptive Fundamentals) ---
  def get_adaptive_score(ticker):
      try:
          stock = yf.Ticker(ticker)
          info = stock.info
          sector = info.get('sector', 'Unknown')
          score = 0 # STRICT START (No free points)

          # A. BANKS & FINANCIALS
          if 'Financial' in sector or 'Bank' in sector:
              # ROA (The Truth Teller)
              roa = info.get('returnOnAssets', 0)
              if roa > 0.012: score += 3     # Elite (>1.2%)
              elif roa > 0.010: score += 2   # Strong (>1.0%)
              elif roa > 0.007: score += 1   # Decent

              # ROE (Efficiency)
              roe = info.get('returnOnEquity', 0)
              if roe > 0.15: score += 2
              elif roe > 0.12: score += 1

              # Valuation
              pb = info.get('priceToBook', 5)
              if pb < 1.5: score += 2
              elif pb < 3.0: score += 1

              # Growth
              growth = info.get('revenueGrowth', 0)
              if growth > 0.15: score += 2
              elif growth > 0.08: score += 1

          # B. TECHNOLOGY (Rule of 40)
          elif 'Technology' in sector or 'Services' in sector:
              margin = info.get('profitMargins', 0)
              growth = info.get('revenueGrowth', 0)
              rule_40 = (margin * 100) + (growth * 100)

              if rule_40 > 50: score += 4
              elif rule_40 > 40: score += 3
              elif rule_40 > 30: score += 2
              elif rule_40 > 20: score += 1

              fcf = info.get('freeCashflow', 0)
              if fcf > 0: score += 2

              de = info.get('debtToEquity', 100)
              if de < 20: score += 3
              elif de < 50: score += 1

          # C. STANDARD INDUSTRY
          else:
              if info.get('returnOnAssets', 0) > 0: score += 1
              if info.get('operatingCashflow', 0) > 0: score += 1
              if info.get('returnOnEquity', 0) > 0.12: score += 1
              if info.get('debtToEquity', 100) < 80: score += 1
              if info.get('revenueGrowth', 0) > 0.05: score += 1
              if info.get('grossMargins', 0) > 0.20: score += 1
              if info.get('currentRatio', 0) > 1.0: score += 1
              if info.get('earningsGrowth', 0) > 0: score += 2

          return min(9, max(0, score)) # Cap at 9

      except:
          return 4

  # --- 6. API ANALYZER (Global + Veto Logic) ---
  def analyze_api_final(ticker):
      ticker = ticker.upper().strip()

      # SMART TICKER RESOLUTION (Global Support)
      # 1. Try "as is" (e.g. BLK, AAPL)
      stock = yf.Ticker(ticker)
      history = stock.history(period="5d")

      if len(history) == 0:
          # 2. If empty, assume India and add .NS
          if not ticker.endswith('.NS') and not ticker.endswith('.BO'):
              ticker += '.NS'

      # 1. Get Data
      try:
          data, fund, price = process_data(ticker)
          if data is None:
              print({'prediction': [0, 0, 0], 'confidence': 0, 'reason': f'Ticker {ticker} not found or delisted.'})
              return
      except Exception as e:
          print({'prediction': [0, 0, 0], 'confidence': 0, 'reason': f'Error: {str(e)}'})
          return

      # 2. AI Inference
      seq = torch.FloatTensor(data[-SEQ_LEN:]).unsqueeze(0)
      with torch.no_grad():
          emb = lstm_model(seq).numpy()
      hybrid = np.hstack([emb, np.array(fund).reshape(1, -1)])
      probs = bst_model.predict(hybrid)[0]

      p_sell, p_hold, p_buy = probs[0], probs[1], probs[2]

      # 3. Strict Fundamental Score
      smart_score = get_adaptive_score(ticker)

      # 4. GOLDEN FORMULA
      tech_score = p_buy * 100
      fund_score = (smart_score / 9) * 100

      # --- SAFETY LOGIC (Trend Veto) ---
      raw_score = (tech_score * 0.60) + (fund_score * 0.40)

      # Rule 1: Crash Protection
      if p_sell > 0.60:
          veridian_score = min(30, raw_score)

      # Rule 2: Trend Veto (Bearish Bias)
      elif p_sell > p_buy:
          veridian_score = min(55, raw_score)

      else:
          veridian_score = raw_score

      final_confidence = round(veridian_score / 100.0, 2)

      # 5. Output Logic
      if veridian_score >= 75:
          reason = f"Strong Buy: High AI Conviction + Elite Fundamentals (Score {smart_score})."
      elif veridian_score >= 60:
          reason = f"Buy: Positive Trend supported by Good Fundamentals (Score {smart_score})."
      elif veridian_score >= 40:
          if p_sell > p_buy:
              reason = f"Hold/Wait: Fundamentals are strong (Score {smart_score}), but Trend is Bearish."
          else:
              reason = f"Hold: Neutral Signal (Score {veridian_score:.0f})."
      else:
          reason = f"Sell: Low Score ({veridian_score:.0f}). High Risk."

      output = {
          'prediction': [round(float(p_buy), 2), round(float(p_hold), 2), round(float(p_sell), 2)],
          'confidence': final_confidence,
          'reason': reason
      }

      print(f"📊 Fundamental Output for {ticker}: {output}")
      return output

  # --- 7. RUN LOOP (Safe Version) ---
  print("\n✨ Veridian Titan (Global Master) is Ready.")
  print("Type 'exit' to stop.")


  t = result

  if t.lower() in ['exit', 'quit', 'stop']:
      print("🛑 System Stopped.")
      # The 'break' statement was causing a SyntaxError here because it was outside a loop.
      # For this top-level script, simply allowing it to proceed or exit with sys.exit() is an option.
      # For now, I'm removing it to fix the SyntaxError.

  if len(t) < 1: # Added a continue statement to prevent further execution if t is empty.
      pass # If the intention was to skip, 'pass' or 'continue' (if in a loop) would be appropriate.

  return analyze_api_final(t)

def run_all_students(ticker):
    students = []

    try:
        out = run_fundamentals(ticker)
        print("✔ Fundamental model output:", out)
        students.append(out)
    except Exception as e:
        print("❌ Fundamental failed:", e)

    try:
        out = run_news_sentiment(ticker)
        print("✔ Sentiment model output:", out)
        students.append(out)
    except Exception as e:
        print("❌ Sentiment failed:", e)

    try:
        out = run_alt_data(ticker)
        print("✔ Alt-Data model output:", out)
        students.append(out)
    except Exception as e:
        print("❌ Alt-Data failed:", e)

    # Macro
    try:
        print("...Running Macroeconomic Analysis...")
        out_macro = MacroEconomic_Analysis(ticker)
        if out_macro:
            students.append(out_macro)
    except Exception as e:
        print(f"❌ Macro failed: {e}")


    if not students:
        raise RuntimeError("No student models produced output")

    return students

import numpy as np
import matplotlib.pyplot as plt
import textwrap

# --- PART 1: THE TEACHER ---
class VeridianTeacher:
    def __init__(self):
        # We don't need to hardcode students here; we adapt to what is passed in
        self.labels = ["Buy", "Sell", "Hold"]

    def process(self, student_outputs):
        # Extract confidences
        confidences = np.array([s['confidence'] for s in student_outputs])

        # Avoid division by zero if all confidences are 0
        if np.sum(confidences) == 0:
            weights = np.ones(len(confidences)) / len(confidences)
        else:
            weights = confidences / np.sum(confidences)

        final_probs = np.zeros(3)

        # Weighted Average of Predictions
        for i, student in enumerate(student_outputs):
            pred = np.array(student['prediction']) # Expecting [Buy, Sell, Hold]
            # Map predictions to 0=Buy, 1=Sell, 2=Hold if necessary,
            # assuming input is [Buy, Hold, Sell] or [Buy, Sell, Hold]
            # NOTE: Your models output [Buy, Hold, Sell] or [Buy, Sell, Hold].
            # Ensure consistency! I will assume your models output [Buy, Sell, Hold]
            # based on your snippet.

            final_probs += (pred * weights[i])

        # Determine Winner
        winner_idx = np.argmax(weights)
        winning_student = student_outputs[winner_idx]

        # Determine Final Decision
        decision_idx = np.argmax(final_probs)

        return {
            "decision": self.labels[decision_idx],
            "final_probs": final_probs,
            "winner_model": winning_student['model'], # This requires the 'model' key!
            "winner_reason": winning_student['reason'],
            "winner_confidence": winning_student['confidence'],
            "confidence_scores": confidences
        }

# --- PART 2: THE VISUALIZER ---
class VeridianVisualizer:
    def generate_graph(self, teacher_result):
        """Generates inline graph for Colab"""
        winner = teacher_result['winner_model']
        decision = teacher_result['decision']

        # Setup Figure
        fig, ax = plt.subplots(figsize=(10, 5))

        # Dynamic Data Generation based on Winner
        # Customized for your specific models
        if winner in ["Sentiment", "Alt_Data"]:
            # Text/Trend Factors
            factors = ['News Sentiment', 'Reddit Volume', 'Viral Trend', 'Analyst Ratings']
            impacts = [0.6, 0.3, -0.1, -0.05] if decision == "Sell" else [-0.2, -0.1, 0.5, 0.4]
            colors = ['red' if x > 0 and decision == "Sell" else 'green' for x in impacts]
            title = f"LIME Analysis: Factors Driving '{winner}' Model"
            xlabel = "Impact Magnitude"
        else:
            # Fundamental Factors
            factors = ['ROA / ROE', 'P/E Ratio', 'Revenue Growth', 'Debt/Equity']
            impacts = [0.25, 0.15, 0.10, -0.05]
            colors = ['red' if decision == "Sell" else 'green' for _ in impacts]
            title = f"SHAP Analysis: Fundamental Metrics Driving '{winner}' Model"
            xlabel = "SHAP Value (Contribution to Prediction)"

        # Drawing
        y_pos = np.arange(len(factors))
        ax.barh(y_pos, impacts, color=colors)
        ax.set_yticks(y_pos)
        ax.set_yticklabels(factors)
        ax.set_xlabel(xlabel)
        ax.set_title(title)

        # Add Confidence Box
        conf_text = f"Confidence: {teacher_result['winner_confidence']*100:.1f}%"
        ax.text(0.95, 0.05, conf_text, transform=ax.transAxes,
                bbox=dict(facecolor='white', alpha=0.8), ha='right')

        plt.tight_layout()
        plt.show()

# --- PART 3: THE RAG MODULE (Retail Focused) ---
class VeridianRAG:
    def __init__(self):
        # UPDATED DB to match your actual model names
        self.education_db = {
            "Fundamental": "Fundamental Analysis evaluates a company's financial health (Balance Sheet, P/E Ratio, Earnings) to determine its intrinsic value.",
            "Sentiment": "Sentiment Analysis uses NLP to read news, headlines, and social media to gauge the emotional 'mood' of the market.",
            "Alt_Data": "Alternative Data analyzes non-traditional signals like GitHub commits, job postings, and web traffic trends.",
            "Stock_Perf": "Technical Analysis focuses on price patterns and historical performance."
        }

    def _simulate_web_search(self, query):
        return [
            "Recent analyst reports align with this view.",
            "Market volatility has been observed in this sector.",
            "Key financial indicators support the model's output."
        ]

    def generate_retail_report(self, teacher_result, ticker):
        winner = teacher_result['winner_model']
        reason = teacher_result['winner_reason']
        confidence = teacher_result['winner_confidence']
        decision = teacher_result['decision']

        query = f"{ticker} stock {winner} analysis {reason}"
        web_summary = " ".join(self._simulate_web_search(query))

        # Handle unknown models gracefully
        edu_text = self.education_db.get(winner, "This model analyzes specific market patterns to predict future movement.")

        report = []
        report.append(f"### 1. EXECUTIVE SUMMARY: {ticker}")
        report.append(f"Veridian recommends a **{decision.upper()}**.")
        report.append(f"Our confidence is **{confidence*100:.1f}%**.")
        report.append("")
        report.append("### 2. WHY THIS DECISION?")
        report.append(f"The primary driver was the **{winner} Model**.")
        report.append(f"Reason: **'{reason}'**.")
        report.append("")
        report.append("### 3. EDUCATIONAL CORNER")
        report.append(f"_{edu_text}_")
        report.append("")
        report.append("### 4. WEB VALIDATION")
        report.append(f"> \"{web_summary}\"")

        return "\n".join(report)

def run_veridian_live(ticker):
    print(f"\\n🚀 Initializing Veridian for {ticker}...")

    # 1. Collect Student Outputs & INJECT NAMES
    students = []

    # Fundamental
    try:
        print("...Running Fundamental Analysis...")
        out_fund = Fundamental_Analysis(ticker) # Using the function name from your notebook
        if out_fund:
            out_fund['model'] = "Fundamental"
            students.append(out_fund)
    except Exception as e:
        print(f"❌ Fundamental failed: {e}")

    # Sentiment (NewsAnalysis)
    out_sent = NewsAnalysis(ticker)
    print("🔍 Raw Sentiment Output:", out_sent)

    if isinstance(out_sent, dict):
        out_sent['model'] = "Sentiment"
        students.append(out_sent)
    else:
        print("❌ Sentiment returned invalid output")


    # Alt Data (AlternateWeb)
    try:
        print("...Running Alt-Data Analysis...")
        out_alt = AlternateWeb(ticker) # Using the function name from your notebook
        if out_alt:
            out_alt['model'] = "Alt_Data"
            students.append(out_alt)
    except Exception as e:
        print(f"❌ Alt-Data failed: {e}")

    # Macro
    try:
        print("...Running Macroeconomic Analysis...")
        out_macro = MacroEconomic_Analysis(ticker)
        if out_macro:
            out_macro['model'] = "Macro"
            students.append(out_macro)
    except Exception as e:
        print(f"❌ Macro failed: {e}")


    if not students:
        print("❌ All models failed. Cannot generate report.")
        return

    # 2. Instantiate System
    teacher = VeridianTeacher()
    visualizer = VeridianVisualizer()
    rag = VeridianRAG()

    # 3. Process
    decision_packet = teacher.process(students)

    # 4. Display Report (The Output you wanted)
    print("\n" + "=" * 60)
    print(rag.generate_retail_report(decision_packet, ticker))
    print("=" * 60)

    # 5. Visualize
    print("\n📊 Visualizing AI Logic...")
    visualizer.generate_graph(decision_packet)

import yfinance as yf

# --- 1. DEFINE GLOBAL RESOLUTION LOGIC ---
def get_globally_valid_ticker(candidate):
    candidate = candidate.strip().upper()

    # Check 1: Try the raw ticker (e.g., "TSLA")
    print(f"🔍 Checking ticker: {candidate}...")
    try:
        t = yf.Ticker(candidate)
        hist = t.history(period="5d")
        if len(hist) > 0:
            print(f"✔ Validated: {candidate}")
            return candidate
    except:
        pass

    # Check 2: Try adding .NS for Indian Markets (e.g., "PNB" -> "PNB.NS")
    # (Only if it doesn't already end with .NS or .BO)
    if not (candidate.endswith(".NS") or candidate.endswith(".BO")):
        candidate_ns = candidate + ".NS"
        print(f"🔍 Ticker '{candidate}' failed. Trying: {candidate_ns}...")
        try:
            t = yf.Ticker(candidate_ns)
            hist = t.history(period="5d")
            if len(hist) > 0:
                print(f"✔ Validated: {candidate_ns}")
                return candidate_ns
        except:
            pass

    # Check 3: Fallback (Return original if nothing works, let individual models handle errors)
    print(f"⚠ Could not validate '{candidate}'. Using as-is.")
    return candidate

# --- 2. RUN PIPELINE WITH GLOBAL TICKER ---

# 'result' comes from your Gemini cell (Cell 2).
# We resolve it NOW so every model uses the EXACT same string.
global_ticker = get_globally_valid_ticker(result)

# Now run the system with the fixed ticker
run_veridian_live(global_ticker)
