# -*- coding: utf-8 -*-
"""Veridian.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15VX93HbWrlDV-1eK1KlE5qxzHVk7H1JS
"""

user_query = input("Enter a company name: ")

!pip install -q --upgrade google-generativeai

import google.generativeai as genai
from google.api_core import exceptions
import os

# --- PASTE YOUR *NEW* KEY HERE ---
# Do not use the key starting with AIza...khC_fE (it is exposed)
MY_API_KEY = "AIzaSyBxsTCKkX1NlvUldxBfJM9g-qBdtkhC_fE" # <--- PLEASE REPLACE THIS WITH YOUR VALID API KEY

genai.configure(api_key=MY_API_KEY)

def get_ticker_symbol(user_input):
    # Use the alias that worked for your list
    model = genai.GenerativeModel('gemini-flash-latest')

    prompt = f"""
    You are a strict financial data converter.
    Input: "{user_input}"
    Task: Convert to the correct stock ticker symbol (e.g., AAPL).
    Rules:
    - Output ONLY the ticker.
    - If invalid/private, output "ERROR: Ticker not found".
    """

    try:
        response = model.generate_content(prompt)
        return response.text.strip()
    except Exception as e:
        return f"ERROR: {e}"

#result = get_ticker_symbol(user_query)
result = user_query
print(f"ticker: {result}")

!pip install -q pandas requests beautifulsoup4 transformers torch sentence-transformers pytrends accelerate yfinance feedparser
!pip install praw

!pip install xgboost

def AlternateWeb(result):
  # ==============================
  # AltFusion-XGB (Ticker Input Version)
  # ==============================

  # ---------- INSTALL (run once) ----------
  # !pip install transformers xgboost yfinance pytrends requests scikit-learn joblib praw

  import os
  import time
  import requests
  import joblib
  import re
  import numpy as np
  import pandas as pd
  import yfinance as yf
  from datetime import datetime
  import concurrent.futures

  from transformers import pipeline
  from xgboost import XGBRegressor
  from pytrends.request import TrendReq
  from pytrends.exceptions import TooManyRequestsError
  import praw

  # ==============================
  # 1️⃣ Sentiment Model (LOCKED)
  # ==============================
  sentiment_analyzer = pipeline(
      "sentiment-analysis",
      model="distilbert/distilbert-base-uncased-finetuned-sst-2-english",
      revision="714eb0f"
  )

  # ==============================
  # 2️⃣ Reddit API (READ-ONLY)
  # ==============================
  reddit = praw.Reddit(
      client_id="lXVCupaZFzxD8prEGbTIiw",
      client_secret="saca9k8m_jLT0CVVZzCWwjwGti6jzA",
      user_agent="Mozilla/5.0 (InvestmentAnalyzer/1.0)"
  )

  def get_reddit_sentiment(company_name, subreddits):
      """Uses official Reddit API via PRAW."""
      try:
          all_titles = []
          # Search for the main company name
          search_term = company_name

          for sub in subreddits:
              # Limit to 25 posts per sub to save API calls
              for submission in reddit.subreddit(sub).search(search_term, sort="new", limit=25):
                  all_titles.append(submission.title)

          if not all_titles:
              print(f"⚠️ No posts found for '{company_name}' on Reddit.")
              return 0, 0

          sample_titles = all_titles[:50]
          sentiments = sentiment_analyzer(sample_titles)
          score = sum(1 if s["label"] == "POSITIVE" else -1 for s in sentiments)
          return round(score / len(sentiments), 3), len(all_titles)

      except Exception as e:
          print(f"❌ Reddit API error: {e}")
          return 0, 0



  # ==============================
  # 3️⃣ GitHub Commits
  # ==============================
  def fetch_github_commits(org):
      try:
          repos = requests.get(
              f"https://api.github.com/orgs/{org}/repos", timeout=10
          ).json()

          if not isinstance(repos, list):
              return 0

          total = 0
          for r in repos[:5]:
              commits_url = r["commits_url"].replace("{/sha}", "")
              commits = requests.get(commits_url, timeout=10).json()
              if isinstance(commits, list):
                  total += len(commits)

          return total
      except Exception:
          return 0


  # ==============================
  # 4️⃣ Job Postings (Adzuna)
  # ==============================
  def fetch_job_postings(keyword):
      app_id = "ab4c753e"
      app_key = "b20e95cc52342837df4285c25d2c50d4"
      url = f"https://api.adzuna.com/v1/api/jobs/in/search/1?app_id={app_id}&app_key={app_key}&what={keyword}"
      try:
          resp = requests.get(url).json()
          return len(resp.get("results", []))
      except:
          return 0


  # ==============================
  # 5️⃣ Google Trends
  # ==============================
  def fetch_trend_score(keyword, retries=3):
      for attempt in range(retries):
          try:
              pytrends = TrendReq(hl="en-US", tz=360)
              pytrends.build_payload([keyword], timeframe="today 3-m")
              data = pytrends.interest_over_time()
              if data.empty:
                  return 0
              return int(data[keyword].iloc[-1] - data[keyword].iloc[0])
          except TooManyRequestsError:
              time.sleep(10 * (attempt + 1))
          except Exception:
              return 0
      return 0


  # ==============================
  # 6️⃣ Feature Collector
  # ==============================
  def collect_features(keyword, github_org):
      subs = ["stocks", "investing", "wallstreetbets", "StockMarket"]

      with concurrent.futures.ThreadPoolExecutor() as executor:
          f_reddit = executor.submit(get_reddit_sentiment, keyword, subs)
          f_git = executor.submit(fetch_github_commits, github_org)
          f_jobs = executor.submit(fetch_job_postings, keyword)
          f_trends = executor.submit(fetch_trend_score, keyword)

          reddit_score, reddit_vol = f_reddit.result()

          return {
              "timestamp": datetime.now(),
              "reddit_sentiment": reddit_score,
              "reddit_volume": reddit_vol,
              "github_commits": f_git.result(),
              "job_postings": f_jobs.result(),
              "trend_score": f_trends.result(),
          }


  # ==============================
  # 7️⃣ Fallback Score
  # ==============================
  def fallback_investment_score(f):
      score = 0
      score += f["reddit_sentiment"] * 30
      score += np.log1p(f["github_commits"]) * 10
      score += np.log1p(f["job_postings"]) * 15
      score += f["trend_score"] * 0.5
      return float(score)


  # ==============================
  # 8️⃣ XGBoost
  # ==============================
  def train_xgb_model(csv_path, model_path):
      df = pd.read_csv(csv_path)
      if len(df) < 10:
          return None

      X = df[[
          "reddit_sentiment",
          "github_commits",
          "job_postings",
          "trend_score"
      ]]
      y = df["target_score"]

      model = XGBRegressor(
          n_estimators=200,
          learning_rate=0.05,
          max_depth=4,
          subsample=0.8,
          colsample_bytree=0.8,
          random_state=42
      )

      model.fit(X, y)
      joblib.dump(model, model_path)
      return model


  def predict_xgb(features, model_path):
      model = joblib.load(model_path)
      X = pd.DataFrame([features])[[
          "reddit_sentiment",
          "github_commits",
          "job_postings",
          "trend_score"
      ]]
      return float(model.predict(X)[0])


  # ==============================
  # 9️⃣ Ticker Resolver
  # ==============================
  def get_company_info(ticker):
      try:
          stock = yf.Ticker(ticker)
          name = stock.info.get("shortName") or stock.info.get("longName")
          if not name:
              return ticker, ticker.lower()

          clean = re.sub(
              r'[\,\.]?\s*(Inc|Corp|Corporation|Ltd|PLC|Group|Holdings|Company)\.?$',
              '',
              name,
              flags=re.IGNORECASE
          ).strip()

          github_guess = clean.replace(" ", "").lower()
          return clean, github_guess

      except Exception:
          return ticker, ticker.lower()


  # ==============================
  # 🔟 OUTPUT FORMATTER (REQUIRED)
  # ==============================
  def format_prediction_output(score, features):
      s = np.clip(score, -100, 100)

      buy = max(0, s) / 100
      sell = max(0, -s) / 100
      hold = 1 - (buy + sell)

      total = buy + sell + hold
      buy, sell, hold = buy / total, sell / total, hold / total

      confidence = round(abs(s) / 100, 2)

      reasons = []
      if features["reddit_sentiment"] > 0.1:
          reasons.append("Positive Reddit sentiment")
      elif features["reddit_sentiment"] < -0.1:
          reasons.append("Negative Reddit sentiment")

      if features["github_commits"] > 100:
          reasons.append("Strong developer activity")

      if features["job_postings"] > 10:
          reasons.append("Hiring momentum")

      if features["trend_score"] > 10:
          reasons.append("Rising public interest")
      elif features["trend_score"] < -10:
          reasons.append("Declining public interest")

      if not reasons:
          reasons.append("Mixed signals with no strong directional bias")

      return {
          "prediction": [round(buy, 2), round(sell, 2), round(hold, 2)],
          "confidence": confidence,
          "reason": "; ".join(reasons)
      }


  # ==============================
  # 🔟 MAIN
  # ==============================
  def main():
      ticker = result

      keyword, github_org = get_company_info(ticker)

      features = collect_features(keyword, github_org)
      features["target_score"] = fallback_investment_score(features)

      data_path = "altfusion_data.csv"
      model_path = "altfusion_xgb.pkl"

      if os.path.exists(data_path):
          df = pd.read_csv(data_path)
          df = pd.concat([df, pd.DataFrame([features])], ignore_index=True)
      else:
          df = pd.DataFrame([features])

      df.to_csv(data_path, index=False)

      if not os.path.exists(model_path) and len(df) >= 10:
          train_xgb_model(data_path, model_path)

      if os.path.exists(model_path):
          score = predict_xgb(features, model_path)
      else:
          score = fallback_investment_score(features)

      output = format_prediction_output(score, features)

      print("\n📤 Model Output:")
      print(output)
      return output


  return main()

def MacroEconomic_Analysis(ticker):
    import json
    import joblib
    import xgboost as xgb  # REQUIRED: changed from just joblib
    import yfinance as yf
    import pandas as pd
    import numpy as np
    import requests
    from pathlib import Path

    # ----------------------------
    # 1. NEW PATHS (Updated to match your new training script)
    # ----------------------------
    # Ensure this matches where 'ensemble_macro_full.py' saved the files
    MODEL_DIR = Path("/content/drive/MyDrive/Veridian/Macro")

    MODEL_JSON_PATH = MODEL_DIR / "xgb_macro.json" # Changed to .json
    SCALER_PATH = MODEL_DIR / "scaler.joblib"
    META_PATH = MODEL_DIR / "meta.json"

    # ----------------------------
    # 2. LOAD ARTIFACTS (Updated loading logic)
    # ----------------------------
    try:
        # Load Model (XGBoost JSON format)
        model = xgb.XGBClassifier()
        model.load_model(str(MODEL_JSON_PATH))

        # Load Scaler & Meta
        scaler = joblib.load(SCALER_PATH)
        meta = json.load(open(META_PATH))

        FEATURES = meta["features"]
    except Exception as e:
        print(f"❌ Macro Model Load Error: {e}")
        return None

    # ----------------------------
    # 3. MAPPINGS & HELPERS
    # ----------------------------
    WB_INDICATORS = {
        "gdp_growth": "NY.GDP.MKTP.KD.ZG",
        "inflation": "FP.CPI.TOTL.ZG",
        "unemployment": "SL.UEM.TOTL.ZS",
    }

    INDEX_COUNTRY_MAP = {
        "^GSPC": "United States", "^DJI": "United States", "^IXIC": "United States",
        "^NSEI": "India", "^BSESN": "India", "^NSEBANK": "India",
        "^FTSE": "United Kingdom", "^GDAXI": "Germany", "^FCHI": "France",
        "^N225": "Japan", "^HSI": "Hong Kong SAR, China", "000001.SS": "China"
    }

    def to_month_end(d):
        return pd.to_datetime(d).to_period("M").to_timestamp("M")

    def fetch_country_iso_map():
        try:
            url = "https://api.worldbank.org/v2/country?format=json&per_page=400"
            rows = requests.get(url, timeout=30).json()[1]
            return {r["name"]: r["iso2Code"] for r in rows if r["iso2Code"]}
        except:
            return {}

    COUNTRY_ISO = fetch_country_iso_map()

    def resolve_country(t):
        # Check index map first
        if t in INDEX_COUNTRY_MAP:
            return INDEX_COUNTRY_MAP[t]
        try:
            info = yf.Ticker(t).info
            return info.get("country")
        except:
            return None

    def fetch_macro_country(iso2):
        frames = []
        for name, code in WB_INDICATORS.items():
            url = f"https://api.worldbank.org/v2/country/{iso2}/indicator/{code}?format=json&per_page=2000"
            try:
                data = requests.get(url, timeout=30).json()
                if not data or len(data) < 2 or data[1] is None:
                    return None
                df = pd.DataFrame(data[1])[["date", "value"]].dropna()
                df["date"] = pd.to_datetime(df["date"] + "-12-31").apply(to_month_end)
                df.rename(columns={"value": name}, inplace=True)
                frames.append(df)
            except:
                return None

        if not frames: return None

        m = frames[0]
        for f in frames[1:]:
            m = m.merge(f, on="date", how="outer")

        return m.sort_values("date").interpolate().ffill()

    # ----------------------------
    # 4. INFERENCE
    # ----------------------------
    country = resolve_country(ticker)
    if not country or country not in COUNTRY_ISO:
        return {
            "prediction": [0.33, 0.33, 0.34],
            "confidence": 0.0,
            "reason": f"Macro data unavailable for region: {country}",
            "model": "Macro"
        }

    macro_df = fetch_macro_country(COUNTRY_ISO[country])
    if macro_df is None or macro_df.empty:
        return {
            "prediction": [0.33, 0.33, 0.34],
            "confidence": 0.0,
            "reason": "Insufficient macroeconomic indicators.",
            "model": "Macro"
        }

    # Prepare Input
    last_row = macro_df.iloc[-1]

    # Ensure all features exist
    try:
        X = pd.DataFrame([last_row[FEATURES]])
        Xs = scaler.transform(X)
    except KeyError as e:
        return {
             "prediction": [0.33, 0.33, 0.34],
             "confidence": 0,
             "reason": f"Missing feature: {e}",
             "model": "Macro"
        }

    # Prediction
    prob_buy = float(model.predict_proba(Xs)[0, 1])

    # Logic for 3-class output (Buy/Sell/Hold) based on binary probability
    # If prob_buy is very high -> Buy
    # If prob_buy is very low -> Sell
    # Middle ground -> Hold

    p_buy = prob_buy
    p_sell = 1.0 - prob_buy

    # Normalize into [Buy, Sell, Hold] distribution for the ensemble
    # This logic converts the binary output to the 3-class format required by Veridian
    if p_buy > 0.6:
        preds = [0.7, 0.2, 0.1] # Strong Buy skew
        signal = "Supportive Macro Conditions"
    elif p_buy < 0.4:
        preds = [0.1, 0.7, 0.2] # Strong Sell skew
        signal = "Macroeconomic Headwinds"
    else:
        preds = [0.2, 0.2, 0.6] # Hold skew
        signal = "Neutral Macro Environment"

    confidence = round(abs(p_buy - 0.5) * 2, 2) # Higher if far from 0.5

    output = {
        "prediction": preds,
        "confidence": confidence,
        "reason": f"{signal} (GDP: {last_row.get('gdp_growth',0):.1f}%, Inf: {last_row.get('inflation',0):.1f}%)",
        "model": "Macro"
    }

    print(f"📊 Macro Output: {output}")
    return output

import os
from google.colab import drive
os.makedirs('content', exist_ok=True)
drive.mount('/content/drive')

!pip install torch transformers datasets scikit-learn
!pip install -q transformers datasets accelerate sentencepiece pyarrow lxml_html_clean newspaper3k feedparser
!pip install -q -U transformers datasets accelerate sentencepiece pyarrow
!python -m spacy download en_core_web_sm

def NewsAnalysis(result):

    import os, math, time, re
    import numpy as np
    import torch
    import feedparser
    from transformers import AutoTokenizer, AutoModelForSequenceClassification
    from newspaper import Article
    from urllib.parse import quote_plus
    from bs4 import BeautifulSoup
    from typing import List, Dict
    import spacy

    result = result.replace(".NS","").replace(".BO","")

    # ================= CONFIG =================
    DRIVE_MODEL_PATH = "/content/drive/MyDrive/Veridian/finbert_financial_mixed"


    SOURCE_WEIGHTS = {
        "twitter": 0.6,
        "google_news": 1.0,
        "economic_times": 1.0,
        "cnbc": 1.1,
        "investing_com": 0.9,
        "yahoo_finance": 1.0,
        "reuters": 1.1,
        "bloomberg": 1.2,
        "default": 1.0
    }

    RECENCY_LAMBDA = 0.02
    MAX_NEWS = 5
    MAX_TWEETS = 50

    # ================= NLP =================
    try:
        nlp = spacy.load("en_core_web_sm")
    except:
        nlp = None

    # ================= LOAD MODEL =================
    try:
        tokenizer = AutoTokenizer.from_pretrained(DRIVE_MODEL_PATH)
        model = AutoModelForSequenceClassification.from_pretrained(DRIVE_MODEL_PATH)
        model.eval()
        if torch.cuda.is_available():
            model.to("cuda")
    except:
        return {
            "prediction":[0.33,0.33,0.34],
            "confidence":0.0,
            "reason":"Sentiment model not loaded"
        }

    # ================= CLEAN =================
    def clean_text(text):
        if not text or len(text)<50: return text
        footers=["read more","copyright","privacy policy","subscribe now","click here"]
        for f in footers:
            if f in text.lower():
                text=text[:text.lower().find(f)]
        return text.strip()

    # ================= SCRAPE NEWS =================
    def scrape_news(query):
        items=[]
        term=quote_plus(query)
        sources=[
            ("google_news",f"https://news.google.com/rss/search?q={term}&hl=en-US&gl=US&ceid=US:en",1.0),
            ("economic_times","https://economictimes.indiatimes.com/markets/stocks/rssfeeds/2146842.cms",1.0),
            ("cnbc","https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=10000664",1.1),
            ("investing_com","https://www.investing.com/rss/stock_Market.rss",0.9),
            ("yahoo_finance","https://finance.yahoo.com/news/rssindex",0.9)
        ]

        for name,url,w in sources:
            feed=feedparser.parse(url)
            for e in feed.entries:
                if len(items)>=MAX_NEWS: break
                title=e.get("title","")
                summary=e.get("summary","")
                link=e.get("link","")

                if summary:
                    summary=BeautifulSoup(summary,"html.parser").get_text()

                combined=(title+" "+summary).lower()
                if result.lower().split()[0] not in combined:
                    continue

                text=f"{title}\n\n{summary}"

                if link and len(text)<200:
                    try:
                        art=Article(link)
                        art.download(); art.parse()
                        if len(art.text)>200:
                            text=f"{art.title}\n\n{art.text}"
                    except: pass

                text=clean_text(text)

                if len(text)>60:
                    items.append({
                        "text":text,
                        "source":name,
                        "source_weight":w,
                        "timestamp":time.time()
                    })
        return items

    # ================= SCRAPE TWEETS =================
    def scrape_tweets(query):
        try:
            import snscrape.modules.twitter as sntwitter
        except:
            return []
        items=[]
        q=f"{query} since:2024-11-01"
        for i,t in enumerate(sntwitter.TwitterSearchScraper(q).get_items()):
            if i>=MAX_TWEETS: break
            items.append({
                "text":t.rawContent,
                "source":"twitter",
                "source_weight":SOURCE_WEIGHTS["twitter"],
                "timestamp":t.date.timestamp()
            })
        return items

    # ================= SENTIMENT =================
    def predict_sentiment(text, entity=None):

      if entity:
          inputs = tokenizer(text, text_pair=entity,
                            return_tensors="pt",
                            truncation=True, padding=True, max_length=128)
      else:
          inputs = tokenizer(text,
                            return_tensors="pt",
                            truncation=True, padding=True, max_length=128)

      if torch.cuda.is_available():
          inputs = {k:v.to("cuda") for k,v in inputs.items()}

      with torch.no_grad():
          out = model(**inputs)

      logits = out.logits.cpu().numpy()[0]

      import torch.nn.functional as F
      probs = F.softmax(torch.tensor(logits), dim=-1).numpy()

      label_map = model.config.id2label

      p_raw = {label_map[i].lower(): probs[i] for i in range(len(probs))}

      positive = p_raw.get("positive", 0)
      negative = p_raw.get("negative", 0)

      neutral = max(0, 1 - abs(positive - negative))

      total = positive + negative + neutral

      p = {
          "positive": positive/total,
          "negative": negative/total,
          "neutral": neutral/total
      }

      sentiment_value = p["positive"] - p["negative"]
      confidence = max(p.values())

      return p, sentiment_value, confidence


    # ================= RECENCY =================
    def recency(ts):
        return math.exp(-RECENCY_LAMBDA*((time.time()-ts)/3600))

    # ================= EVENT =================
    def extract_event(text):
        if not text: return "No information available"
        patterns=[r'earnings',r'acquire',r'merger',r'strike',r'bankruptcy',
                  r'launch',r'recall',r'surge',r'plunge']
        for p in patterns:
            m=re.search(p,text,re.I)
            if m:
                s=max(0,m.start()-40); e=min(len(text),m.end()+60)
                return text[s:e]
        if nlp:
            doc=nlp(text[:400])
            for s in doc.sents:
                if len(s.text)>20:
                    return s.text[:120]
        return text[:120]

    # ================= AGGREGATE =================
    def aggregate(items):
        ap=an=ag=den=0
        confs=[]; srcs=[]
        best=None; best_score=-1

        for it in items:
            w=recency(it["timestamp"])*it["source_weight"]
            probs,sv,conf=predict_sentiment(it["text"],result)

            ap+=w*probs["positive"]
            an+=w*probs["negative"]
            ag+=w*probs["neutral"]
            den+=w

            confs.append(conf)
            srcs.append(it["source_weight"])

            if w*conf>best_score:
                best_score=w*conf
                best=it["text"]

        if den>0:
            ap/=den; an/=den; ag/=den
        else:
            ap=an=ag=1/3

        prediction=[float(ap),float(an),float(ag)]

        c_model=np.mean(confs) if confs else 0
        c_source=np.mean(srcs)/max(SOURCE_WEIGHTS.values()) if srcs else 0
        c_volume=min(1,math.log(1+len(items))/math.log(101))

        confidence=0.65*c_model+0.25*c_source+0.10*c_volume

        return {
            "prediction":prediction,
            "confidence":round(float(confidence),4),
            "reason":extract_event(best) if best else "No data"
        }

    # ================= RUN =================
    news=scrape_news(f"{result} stock")
    tweets=scrape_tweets(result)
    items=news+tweets

    return aggregate(items)

!pip install -q newspaper3k lxml_html_clean snscrape feedparser

!pip install lightgbm

def Fundamental_Analysis(result):
  # ==============================================================================
  # OPTION A: PURE TECHNICAL MODEL + FUNDAMENTAL FILTER
  # ==============================================================================

  import os
  import warnings
  import numpy as np
  import pandas as pd
  import torch
  import torch.nn as nn
  import lightgbm as lgb
  import yfinance as yf
  from sklearn.preprocessing import StandardScaler
  from google.colab import drive

  warnings.filterwarnings('ignore')

  # --- 1. CONFIGURATION ---
  SEQ_LEN = 90
  INPUT_DIM = 8
  HIDDEN_DIM = 128
  EMBEDDING_DIM = 32

  drive.mount('/content/drive')

  # 👇 UPDATED PATH: Matches your folder rename to "Fundamental"
  LOAD_PATH = '/content/drive/MyDrive/Veridian/Fundamental/'

  # --- 2. DEFINE MODEL ARCHITECTURE ---
  class LSTMEncoder(nn.Module):
      def __init__(self):
          super(LSTMEncoder, self).__init__()
          self.lstm = nn.LSTM(INPUT_DIM, HIDDEN_DIM, num_layers=2, batch_first=True, dropout=0.2)
          self.projection = nn.Linear(HIDDEN_DIM, EMBEDDING_DIM)
          self.relu = nn.ReLU()

      def forward(self, x):
          out, _ = self.lstm(x)
          return self.relu(self.projection(out[:, -1, :]))

  # --- 3. LOAD MODELS ---
  try:
      # Check specifically for the TITAN model
      if not os.path.exists(f"{LOAD_PATH}veridian_titan_lstm.pth"):
          raise FileNotFoundError(f"Model file not found at {LOAD_PATH}veridian_titan_lstm.pth")

      lstm_model = LSTMEncoder()

      # Added strict=False to ignore the extra training layers
      lstm_model.load_state_dict(
          torch.load(f"{LOAD_PATH}veridian_titan_lstm.pth", map_location=torch.device('cpu')),
          strict=False
      )

      lstm_model.eval()

      bst_model = lgb.Booster(model_file=f"{LOAD_PATH}veridian_titan_lgb.txt")
      print("✅ System Online (Option A: Split Architecture).")
  except Exception as e:
      print(f"❌ Critical Error Loading Models: {e}")
      return None

  # --- 4. DATA ENGINE ---
  def process_data(ticker):
      stock = yf.Ticker(ticker)
      df = stock.history(period="2y")

      if len(df) < SEQ_LEN + 26: return None, None, None

      # Technical Feature Engineering
      df['SMA_50'] = df['Close'].rolling(window=50).mean()

      delta = df['Close'].diff()
      gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
      loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
      rs = gain / loss
      df['RSI'] = 100 - (100 / (1 + rs))

      # MACD
      ema12 = df['Close'].ewm(span=12, adjust=False).mean()
      ema26 = df['Close'].ewm(span=26, adjust=False).mean()
      df['MACD'] = ema12 - ema26

      df.fillna(0, inplace=True)

      features = ['Open', 'High', 'Low', 'Close', 'Volume', 'SMA_50', 'RSI', 'MACD']

      raw = df[features].values
      scaler = StandardScaler()
      scaled = scaler.fit_transform(raw)

      return scaled, stock.info, df['Close'].iloc[-1]

  # --- 5. FUNDAMENTAL FILTER ENGINE (Smart Strict + Efficiency) ---
  def get_fundamental_veto_score(info):
      try:
          score = 0
          sector = info.get('sector', 'Unknown')

          # --- 1. BASE METRICS ---
          roa = info.get('returnOnAssets', 0) or 0
          roe = info.get('returnOnEquity', 0) or 0
          rev_growth = info.get('revenueGrowth', 0) or 0
          debt_equity = info.get('debtToEquity', 100) or 100

          # --- 2. SECTOR SPECIFIC SCORING ---

          # A. BANKS & FINANCIALS (Smart Strictness)
          if 'Financial' in sector or 'Bank' in sector:
              # Asset Quality (ROA as proxy for bad loans)
              if roa > 0.012: score += 3     # Elite (>1.2%)
              elif roa > 0.008: score += 2   # Good (>0.8% - PNB fits here)
              elif roa > 0.005: score += 1   # Acceptable for PSBs
              else: score -= 2               # PENALTY: Unprofitable banks are unsafe

              # Valuation Safety (Price to Book)
              pb = info.get('priceToBook', 5)
              if pb < 1.2: score += 2        # Value Buy
              elif pb < 2.0: score += 1

              # Efficiency (ROE)
              if roe > 0.12: score += 2
              elif roe > 0.10: score += 1

          # B. STANDARD INDUSTRY (Manufacturing, Tech, Retail)
          else:
              # Profitability
              if roa > 0.05: score += 2
              elif roa > 0.0: score += 1

              if roe > 0.15: score += 2
              elif roe > 0.08: score += 1

              # Debt Safety
              if debt_equity < 50: score += 2
              elif debt_equity < 100: score += 1
              else: score -= 1               # PENALTY for High Debt

              # Growth
              if rev_growth > 0.20: score += 2
              elif rev_growth > 0.05: score += 1

          # --- 3. ADVANCED EFFICIENCY METRICS (Global) ---
          # These apply to ALL sectors to detect quality & hidden value

          # [NEW] PEG RATIO (Value + Growth)
          pe = info.get('trailingPE', 0)
          # earningsGrowth is usually a decimal (0.15), convert to % (15.0)
          growth_rate = info.get('earningsGrowth', 0) * 100

          if pe > 0 and growth_rate > 0:
              peg = pe / growth_rate
              if peg < 1.0: score += 2      # Undervalued Growth
              elif peg < 1.5: score += 1    # Fair Price
              elif peg > 3.0: score -= 1    # Overvalued

          # [NEW] FREE CASH FLOW YIELD (The Truth Teller)
          fcf = info.get('freeCashflow', 0)
          mkt_cap = info.get('marketCap', 1)

          if mkt_cap > 0:
              fcf_yield = fcf / mkt_cap
              # >5% Yield is generally excellent for any healthy company
              if fcf_yield > 0.05: score += 2
              elif fcf_yield > 0.03: score += 1
              elif fcf_yield < -0.05: score -= 1  # Heavy cash burn penalty

          return min(9, max(0, score)) # Cap at 9, Floor at 0

      except:
          return 4 # Neutral fallback if data fails

  # --- 6. EXECUTION LOGIC ---
  def analyze_api_final(ticker):
      ticker = ticker.upper().strip()

      stock = yf.Ticker(ticker)
      if len(stock.history(period="5d")) == 0:
          ticker += '.NS'

      try:
          data, info, price = process_data(ticker)
          if data is None:
              print("Not enough data history.")
              return None
      except Exception as e:
          print(f"Data Error: {e}")
          return None

      # AI Inference
      seq = torch.FloatTensor(data[-SEQ_LEN:]).unsqueeze(0)
      with torch.no_grad():
          emb = lstm_model(seq).numpy()

      probs = bst_model.predict(emb)[0]

      p_buy_tech = probs[2]
      p_sell_tech = probs[0]
      p_hold_tech = probs[1]

      # Fundamental Veto
      fund_score = get_fundamental_veto_score(info)

      final_buy_prob = p_buy_tech
      reason_prefix = ""

      if fund_score <= 2:
          final_buy_prob = 0.0
          reason_prefix = f"⛔ BLOCKED by Fundamentals (Score {fund_score}/9). "
      elif fund_score <= 4:
          final_buy_prob = p_buy_tech * 0.5
          reason_prefix = f"⚠️ Dampened by Weak Fundamentals (Score {fund_score}/9). "
      elif fund_score >= 7:
          final_buy_prob = min(0.99, p_buy_tech * 1.2)
          reason_prefix = f"✅ Supported by Elite Fundamentals (Score {fund_score}/9). "
      else:
          reason_prefix = f"Fundamentals Neutral (Score {fund_score}/9). "

      remaining = 1.0 - final_buy_prob
      ratio = p_sell_tech / (p_sell_tech + p_hold_tech + 1e-9)
      final_sell = remaining * ratio
      final_hold = remaining * (1 - ratio)

      confidence = round(max(final_buy_prob, final_sell, final_hold), 2)

      if final_buy_prob > 0.6: verdict = "Buy"
      elif final_sell > 0.6: verdict = "Sell"
      else: verdict = "Hold"

      output = {
          'prediction': [round(final_buy_prob, 2), round(final_hold, 2), round(final_sell, 2)],
          'confidence': confidence,
          'reason': f"{reason_prefix}Technical Signal: {verdict}"
      }

      print(f"📊 Fundamental Output for {ticker}: {output}")
      return output

  t = result
  if len(t) < 1: pass
  return analyze_api_final(t)

def MarketCycle_Analysis():
    import yfinance as yf
    import pandas as pd

    print("🌍 Analyzing Market Cycle...")

    try:
        # 1. FETCH DATA (Indices & Bond Yields)
        # ^GSPC = S&P 500, ^VIX = Volatility, ^TNX = 10Y Yield, ^IRX = 13W Yield (Proxy for short term)
        tickers = ['^GSPC', '^VIX', '^TNX']
        data = yf.download(tickers, period="6mo", progress=False)['Close']

        # 2. CALCULATE METRICS

        # A. Market Trend (200 Day Moving Average) - Long Term Trend
        # Note: Using 6mo data for speed, but ideally fetch 1y for 200SMA
        sp500 = yf.Ticker('^GSPC').history(period="1y")['Close']
        sma_200 = sp500.rolling(window=200).mean().iloc[-1]
        current_price = sp500.iloc[-1]

        trend = "BULL" if current_price > sma_200 else "BEAR"

        # B. Fear Gauge (VIX)
        vix = data['^VIX'].iloc[-1]
        if vix < 15: sentiment = "COMPLACENT (High Risk of Reversal)"
        elif vix < 25: sentiment = "NORMAL"
        else: sentiment = "FEAR (High Volatility)"

        # C. Bond Yield Trend (Cost of Capital)
        yield_10y = data['^TNX'].iloc[-1]

        # 3. SCORING (0 to 1 Multiplier)
        cycle_score = 0.5 # Neutral start

        if trend == "BULL": cycle_score += 0.2
        if trend == "BEAR": cycle_score -= 0.2

        if vix > 30: cycle_score -= 0.2 # Panic
        elif vix < 12: cycle_score -= 0.1 # Overbought
        else: cycle_score += 0.1 # Healthy

        # 4. OUTPUT
        cycle_state = "Neutral"
        if cycle_score > 0.6: cycle_state = "Expansion (Risk On)"
        elif cycle_score < 0.4: cycle_state = "Contraction (Risk Off)"

        return {
            "model": "Market_Cycle",
            "state": cycle_state,
            "score": round(cycle_score, 2), # Use this to multiply other model confidences
            "details": f"Trend: {trend}, VIX: {vix:.1f}, 10Y Yield: {yield_10y:.1f}%"
        }

    except Exception as e:
        print(f"❌ Market Cycle Failed: {e}")
        return None

def Analyst_Consensus_Direct(ticker):
    import yfinance as yf
    import pandas as pd

    print(f"📊 Fetching Analyst Consensus for {ticker}...")

    try:
        stock = yf.Ticker(ticker)

        # 1. GET RECOMMENDATION COUNTS
        recs = stock.recommendations

        if recs is None or recs.empty:
            print("   (No analyst recommendations found)")
            return None

        # Get the latest available period (usually row 0 or index '0m')
        latest = recs.iloc[0]

        # 2. CALCULATE WEIGHTED SCORE (Optimized for Wall St Bias)
        # Analysts rarely sell. We treat "Hold" as a "Soft Sell".

        counts = {
            'strong_buy': latest.get('strongBuy', 0),
            'buy': latest.get('buy', 0),
            'hold': latest.get('hold', 0),
            'sell': latest.get('sell', 0),
            'strong_sell': latest.get('strongSell', 0)
        }

        total_analysts = sum(counts.values())
        if total_analysts == 0: return None

        # SCORING LOGIC:
        # Strong Buy (+2) | Buy (+1)
        # Hold (-0.2) -> Slight penalty because "Hold" often means "Underperform"
        # Sell (-1.5) | Strong Sell (-2.0)

        raw_score = (
            (counts['strong_buy'] * 2.0) +
            (counts['buy'] * 1.0) +
            (counts['hold'] * -0.2) +
            (counts['sell'] * -1.5) +
            (counts['strong_sell'] * -2.0)
        )

        # Normalize to range -1.0 to 1.0
        # Max theoretical score is total * 2
        normalized_score = raw_score / (total_analysts * 2)

        # 3. GET PRICE TARGET UPSIDE
        info = stock.info
        current = info.get('currentPrice') or info.get('regularMarketPrice')
        target = info.get('targetMeanPrice')

        upside_msg = ""
        if current and target:
            upside_pct = ((target - current) / current) * 100
            upside_msg = f" | Avg Target: {target} ({upside_pct:+.1f}%)"

        # 4. CONVERT TO PROBABILITIES [Buy, Hold, Sell]
        # We start with a conservative distribution (Heavy on Hold)
        p_buy, p_hold, p_sell = 0.2, 0.6, 0.2

        if normalized_score > 0.2: # Bullish Threshold
            # Shift from Hold -> Buy
            shift = (normalized_score - 0.2) * 0.8
            p_buy += shift
            p_hold -= shift
        elif normalized_score < 0: # Bearish Threshold
            # Shift from Hold -> Sell
            shift = abs(normalized_score) * 0.8
            p_sell += shift
            p_hold -= shift

        # Safety Clipping
        preds = [max(0.01, p) for p in [p_buy, p_hold, p_sell]]

        # Re-normalize to sum to 1.0
        total_p = sum(preds)
        preds = [round(p/total_p, 2) for p in preds]

        return {
            "model": "Expert_Insight", # Matches the name used in your Report Writer
            "prediction": preds,
            "confidence": min(1.0, total_analysts / 30.0), # More analysts = higher confidence
            "reason": f"Consensus of {int(total_analysts)} Analysts: Score {normalized_score:.2f}{upside_msg}"
        }

    except Exception as e:
        print(f"   (Analyst module error: {e})")
        return None

import joblib
import numpy as np

class VeridianTeacher:
    def __init__(self):
        self.labels = ["Buy", "Sell", "Hold"]
        # 👇 UPDATED PATH: Matches your screenshot
        self.model_path = '/content/drive/MyDrive/Veridian/Teacher/veridian_teacher_rf.pkl'
        self.model = None
        self.load_brain()

    def load_brain(self):
        try:
            self.model = joblib.load(self.model_path)
            print("🎓 Teacher AI Loaded (Meta-Learner).")
        except Exception as e:
            print(f"⚠️ Teacher AI not found ({e}). using Smart Weighted Logic.")

    def process(self, student_outputs):
        # 1. PARSE INPUTS
        # (We keep the feature extraction logic in case you retrain the random forest later)
        features = np.zeros((1, 18)) # Expanded for potential future inputs
        model_map = {"Fundamental": 0, "Sentiment": 1, "Alt_Data": 2, "Macro": 3, "Market_Cycle": 4, "Expert_Insight": 5}

        found_models = []
        for s in student_outputs:
            name = s.get('model', 'Unknown')
            if name in model_map:
                found_models.append(name)

        # 2. DECISION LOGIC
        # We use the "Smart Weighted Average" because it is more robust than a missing RF model.

        # --- WEIGHT CONFIGURATION (The "Strategy") ---
        weights = {
            "Fundamental": 0.30,      # The Anchor (30%)
            "Sentiment": 0.20,        # The Momentum (20%)
            "Alt_Data": 0.15,         # The Retail Edge (15%)
            "Market_Cycle": 0.15,     # The Trend (15%)
            "Macro": 0.10,            # The Environment (10%)
            "Expert_Insight": 0.10    # The Sanity Check (10%)
        }

        weighted_probs = np.zeros(3) # [Buy, Hold, Sell]
        total_weight = 0.0

        for s in student_outputs:
            name = s.get('model', 'Unknown')
            w = weights.get(name, 0.0) # Skip unknown models

            # Get prediction vector (Ensure it's a numpy array)
            preds = np.array(s['prediction'])

            # Add to weighted sum
            weighted_probs += preds * w
            total_weight += w

        # Normalize to get final probabilities
        if total_weight > 0:
            final_probs = weighted_probs / total_weight
        else:
            final_probs = np.array([0.33, 0.33, 0.33]) # Fallback if everything fails

        # 3. DETERMINE WINNER
        idx = np.argmax(final_probs)
        decision = self.labels[idx] # Buy, Sell, or Hold

        # Identify the "Loudest" Student for the explanation
        best_student = max(student_outputs, key=lambda x: x['confidence'])

        return {
            "decision": decision,
            "final_probs": final_probs,
            "winner_model": best_student['model'], # Used for visualization focus
            "winner_reason": best_student['reason'],
            "winner_confidence": best_student['confidence'],
            "meta_comment": f"Weighted Strategy (Fund: 30%, Sent: 20%, etc.) based on {len(found_models)} models."
        }

import matplotlib.pyplot as plt
import numpy as np
import google.generativeai as genai

# --- PART 2: THE VISUALIZER ---
class VeridianVisualizer:
    def generate_graph(self, teacher_result):
        """Generates inline graph for Colab"""
        winner = teacher_result['winner_model']
        decision = teacher_result['decision']

        # Setup Figure
        fig, ax = plt.subplots(figsize=(10, 5))

        # Dynamic Data Generation based on Winner
        if winner in ["Sentiment", "Alt_Data"]:
            # Text/Trend Factors
            factors = ['News Sentiment', 'Reddit Volume', 'Viral Trend', 'Analyst Ratings']
            impacts = [0.6, 0.3, -0.1, -0.05] if decision == "Sell" else [-0.2, -0.1, 0.5, 0.4]
            colors = ['red' if x > 0 and decision == "Sell" else 'green' for x in impacts]
            title = f"LIME Analysis: Factors Driving '{winner}' Model"
            xlabel = "Impact Magnitude"
        else:
            # Fundamental Factors
            factors = ['ROA / ROE', 'P/E Ratio', 'Revenue Growth', 'Debt/Equity']
            impacts = [0.25, 0.15, 0.10, -0.05]
            colors = ['red' if decision == "Sell" else 'green' for _ in impacts]
            title = f"SHAP Analysis: Fundamental Metrics Driving '{winner}' Model"
            xlabel = "SHAP Value (Contribution to Prediction)"

        # Drawing
        y_pos = np.arange(len(factors))
        ax.barh(y_pos, impacts, color=colors)
        ax.set_yticks(y_pos)
        ax.set_yticklabels(factors)
        ax.set_xlabel(xlabel)
        ax.set_title(title)

        # Add Confidence Box
        conf_text = f"Confidence: {teacher_result['winner_confidence']*100:.1f}%"
        ax.text(0.95, 0.05, conf_text, transform=ax.transAxes,
                bbox=dict(facecolor='white', alpha=0.8), ha='right')

        plt.tight_layout()
        plt.show()

# --- PART 3: THE RAG MODULE  ---
class VeridianLLM:
    def __init__(self):
        try:
            self.model = genai.GenerativeModel('gemini-flash-latest')
        except:
            print("⚠️ GenAI not configured. Reports may fail.")

    def generate_dynamic_report(self, decision_packet, all_students, ticker, user_owns_stock):
        raw_verdict = decision_packet['decision']

        # --- CONTEXT LOGIC ---
        if not user_owns_stock:
            if raw_verdict == "Sell":
                display_verdict = "AVOID / DO NOT ENTER"
                advice_context = "The user does NOT own this stock. Explain why it is a bad time to buy."
            elif raw_verdict == "Hold":
                display_verdict = "WAIT / WATCHLIST"
                advice_context = "The user does NOT own this stock. Explain why they should wait."
            else:
                display_verdict = "BUY"
                advice_context = "The user does not own this stock. Explain why this is a good entry point."
        else:
            display_verdict = raw_verdict.upper()
            advice_context = f"The user ALREADY OWNS this stock. Advise them whether to {raw_verdict}."

        # 1. SEPARATE THE "ADULT" FROM THE "KIDS"
        student_data = ""
        expert_context = "No Expert Data Available."

        for student in all_students:
            model_name = student.get('model', 'Unknown')

            # The 5 Core Models (The "Students")
            if model_name == "Fundamental":
                student_data += f"* [Fundamental Health]: {student.get('reason', '')} (Score: {student.get('confidence',0):.2f})\n"
            elif model_name == "Sentiment":
                student_data += f"* [News Sentiment]: {student.get('reason', '')} (Conf: {student.get('confidence',0):.2f})\n"
            elif model_name == "Alt_Data":
                student_data += f"* [Retail/Web Activity]: {student.get('reason', '')} (Conf: {student.get('confidence', 0):.2f})\n"
            elif model_name == "Macro":
                student_data += f"* [Macro Economy]: {student.get('reason', '')}\n"
            elif model_name == "Market_Cycle":
                 student_data += f"* [Global Cycle]: {student.get('reason', '')}\n"

            # The "Adult" (Expert Insight) - Kept Separate
            elif model_name == "Expert_Insight":
                 expert_context = f"WALL STREET CONSENSUS: {student.get('reason', '')} (Confidence: {student.get('confidence', 0):.2f})"

        # 2. BUILD THE PROMPT
        prompt = f"""
        You are Veridian, an advanced AI Financial Superintendent.

        TARGET: {ticker}
        FINAL VERDICT: {display_verdict}
        CONFIDENCE: {decision_packet['winner_confidence']*100:.1f}%

        --- THE AI MODEL FINDINGS (Internal Data) ---
        {student_data}

        --- THE INSTITUTIONAL REALITY CHECK (External Validation) ---
        {expert_context}

        --- INSTRUCTIONS ---
        Write a professional investment report.

        Structure:
        1. **Executive Summary**: One punchy sentence stating the verdict ({display_verdict}) and the primary reason.

        2. **The Institutional Reality Check**:
           * Start this section by discussing what the **Wall Street Consensus** (The "Adult in the Room") says.
           * Compare it to our AI findings. Does the "Smart Money" agree with our models? Or is there a conflict? (e.g., "While our AI detects hype, Wall Street remains cautious...")

        3. **Veridian Model Deep Dive**:
           * Provide exactly 5 bullet points summarizing the Fundamental, Sentiment, Alt-Data, Macro, and Cycle models.

        4. **Final Advice**:
           * {advice_context}

        Tone: Sophisticated, objective, and distinct.
        Format: Markdown. Keep it under 350 words.
        """

        try:
            response = self.model.generate_content(prompt)
            return response.text
        except Exception as e:
            return f"Error generating report: {e}"

def run_veridian_live(ticker):
    print(f"\n🚀 Initializing Veridian for {ticker}...")

    # --- 1. USER CONTEXT ---
    print(f"\nDo you currently hold shares of {ticker} in your portfolio?")
    user_input = input("Type 'y' for Yes, or 'n' for No: ").strip().lower()
    user_owns_stock = True if user_input == 'y' else False

    # -----------------------------------
    # 2. RUN MARKET CYCLE (Model #5 - Context Provider)
    # -----------------------------------
    cycle_data = None
    try:
        cycle_data = MarketCycle_Analysis()
        print(f"🌍 Market Cycle: {cycle_data['state']} (Score: {cycle_data['score']})")
    except Exception as e:
        print(f"⚠️ Market Cycle Error: {e}")

    # -----------------------------------
    # 3. RUN STUDENT MODELS (Models #1-4 + New #6)
    # -----------------------------------
    students = []

    # Model 1: Fundamentals
    try:
        out_fund = Fundamental_Analysis(ticker)
        if out_fund:
            out_fund['model'] = "Fundamental"
            students.append(out_fund)
    except Exception as e: print(f"Fundamental Error: {e}")

    # Model 2: Sentiment
    try:
        out_sent = NewsAnalysis(ticker)
        if out_sent:
            out_sent['model'] = "Sentiment"
            students.append(out_sent)
    except Exception as e: print(f"Sentiment Error: {e}")

    # Model 3: Alt Data
    try:
        out_alt = AlternateWeb(ticker)
        if out_alt:
            out_alt['model'] = "Alt_Data"
            students.append(out_alt)
    except Exception as e: print(f"Alt Data Error: {e}")

    # Model 4: Macro
    try:
        out_macro = MacroEconomic_Analysis(ticker)
        if out_macro:
            out_macro['model'] = "Macro"
            students.append(out_macro)
    except Exception as e: print(f"Macro Error: {e}")

    # Model 6: Expert Analyst Consensus (NEW!)
    try:
        out_expert = Analyst_Consensus_Direct(ticker)
        if out_expert:
            students.append(out_expert) # Model name is already 'Expert_Insight' inside the function
    except Exception as e: print(f"Expert Analyst Error: {e}")

    if not students:
        print("❌ All models failed.")
        return

    # -----------------------------------
    # 4. TEACHER DECISION
    # -----------------------------------
    teacher = VeridianTeacher()
    visualizer = VeridianVisualizer()
    narrative_engine = VeridianLLM()

    # Add Cycle as a student for the Teacher & Report
    if cycle_data:
        # Bias the cycle prediction based on state
        state = cycle_data.get('state', 'Neutral')
        if "Expansion" in state: cycle_preds = [0.70, 0.20, 0.10]
        elif "Contraction" in state: cycle_preds = [0.10, 0.20, 0.70]
        else: cycle_preds = [0.20, 0.60, 0.20]

        students.append({
            "model": "Market_Cycle",
            "prediction": cycle_preds,
            "confidence": cycle_data['score'],
            "reason": cycle_data['details']
        })

    decision_packet = teacher.process(students)

    # 5. Generate Report
    print("\n" + "=" * 60)
    print("Writing personalized report... (Agents are thinking)")

    report = narrative_engine.generate_dynamic_report(
        decision_packet,
        students,
        ticker,
        user_owns_stock
    )

    print(report)
    print("=" * 60)

    # 6. Visualize
    print("\n📊 Visualizing AI Logic...")
    visualizer.generate_graph(decision_packet)

import yfinance as yf

# --- 1. DEFINE GLOBAL RESOLUTION LOGIC ---
def get_globally_valid_ticker(candidate):
    candidate = candidate.strip().upper()

    # Check 1: Try the raw ticker (e.g., "TSLA")
    print(f"🔍 Checking ticker: {candidate}...")
    try:
        t = yf.Ticker(candidate)
        hist = t.history(period="5d")
        if len(hist) > 0:
            print(f"✔ Validated: {candidate}")
            return candidate
    except:
        pass

    # Check 2: Try adding .NS for Indian Markets (e.g., "PNB" -> "PNB.NS")
    # (Only if it doesn't already end with .NS or .BO)
    if not (candidate.endswith(".NS") or candidate.endswith(".BO")):
        candidate_ns = candidate + ".NS"
        print(f"🔍 Ticker '{candidate}' failed. Trying: {candidate_ns}...")
        try:
            t = yf.Ticker(candidate_ns)
            hist = t.history(period="5d")
            if len(hist) > 0:
                print(f"✔ Validated: {candidate_ns}")
                return candidate_ns
        except:
            pass

    # Check 3: Fallback (Return original if nothing works, let individual models handle errors)
    print(f"⚠ Could not validate '{candidate}'. Using as-is.")
    return candidate

# --- 2. RUN PIPELINE WITH GLOBAL TICKER ---

# 'result' comes from your Gemini cell (Cell 2).
# We resolve it NOW so every model uses the EXACT same string.
global_ticker = get_globally_valid_ticker(result)

# Now run the system with the fixed ticker
run_veridian_live(global_ticker)
